/*
 * This source file was generated by the Gradle 'init' task
 */
// package main.;
// import Donor;
// import org.example.heart-and-love.donation.Donor;
import java.time.LocalDateTime;

import donation.Donor;
import schedule.Schedule;
import login.*;
public class App {

    public static void main(String[] args) {
// String firstName, String lastName, String email, int householdSize, String password
        System.out.println("Welcome to Heart & Love! We strive to meet the needs of our community!");
        System.out.println("Heat & Love is a work in progress, but our developers have worked hard to create the following functionality \nfrom a donor's perspective:");


        Donor user1 = new Donor("John" , "Doe" , "jd123@example.com" , 13, "123password456");
        System.out.println("\nHi " + user1.getFirstName() +"! Thank you for creating an account with us!");
        LoginPage loginPage = new LoginPage("admin", "password");
        loginPage.login();
        Schedule schedule = new Schedule();
        user1.viewAcceptableDonations();
        System.out.println("\nWe have a donor!\n" + user1.toString() +"\n");
        user1.scheduleDonations("Canned Vegetables", 300000, LocalDateTime.now(), schedule);
        loginPage.logout();

    }
}
